import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemePorvider";
import { Toaster } from "sonner";
import { cookies } from "next/headers";
import { AuthProvider } from "@/providers/AuthProvider";
import GoogleOneTapLogin from "@/auth/GoogleOneTap";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Brandmi",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("accessToken")?.value || null;

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {!token && <GoogleOneTapLogin />}
          <Toaster richColors position="top-center" />
          <AuthProvider initialToken={token}>{children}</AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
